spring.application.name=parking-app

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/parking_app
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# AWS Cognito — OAuth2 Resource Server (JWT)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_5Hq8VEHuN
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_5Hq8VEHuN/.well-known/jwks.json

# Cognito metadata (used in SecurityConfig)
aws.cognito.client-id=1d2sil9s35rb6b6t02c647co98
aws.cognito.user-pool-id=us-east-1_5Hq8VEHuN
